# @package _group_

reddit_test:
  _target_: dpr.data.retriever_data.JsonQASrc
  file: /home/miyoung/suehyun/DPR/data/retriever/reddit/test_examples_v2.json

reddit_train:
  _target_: dpr.data.retriever_data.JsonQASrc
  file: /home/miyoung/suehyun/DPR/data/retriever/reddit/train_v3.json

reddit_val:
  _target_: dpr.data.retriever_data.JsonQASrc
  file: /home/miyoung/suehyun/DPR/data/retriever/reddit/val_v3.json

reddit_val_sample:
  _target_: dpr.data.retriever_data.JsonQASrc
  file: /home/miyoung/suehyun/DPR/data/retriever/reddit/val_v3_sample.json

reddit_val_sample_annotated:
  _target_: dpr.data.retriever_data.JsonSampledQASrc
  file: /home/miyoung/suehyun/DPR/input/retriever/reddit/val_sample_annotated_v1.json
